language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t blueskyzhy/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true blueskyzhy/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "DockerReact"
  evn: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-west-2-683938102574"
  bucket_path: "DockerReact"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY